# Generated by Django 3.1.5 on 2021-01-23 05:14

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='empresas',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='empresas.Empresas'),
        ),
    ]
